ignore:
####
# Ignore Generated Classes
 - "Pods/.*" # ignore pods from code coverage
 - "Libraries/.*" # ignore third party libraries from code coverage
 ####
 # Ignore Tests
 - "*Test/.*" # ignore Tests from code coverage
 ####
 # Ignore UI
 - "**.storyboard" # Storyboards
 - "PokeApp/Conveniences/UI/**" # Custom UI elements
 ####
 # Ignore ViewControllers
 - "PokeApp/Scenes/**/ViewControllers/**"
 - "*ViewController.swift"
 ####
 # Ignore View Related Classes
 - "PokeApp/Scenes/**/Cells/**"
 - "*ViewCell.swift" # CollectionView and TableViewCells
####
# Other Classes
- "UIView+Loading.swift"
- "UIViewControllerExtension.swift"
- "AlertHelper.swift"