ignore:
 - "Pods/.*" # ignore pods from code coverage
 - "Libraries/.*" # ignore third party libraries from code coverage
 - "*Test/.*" # ignore Tests from code coverage
 - "**.storyboard" # ignore Storyboards
 - "PokeApp/Conveniences/UI/**" # ignore UI elements
 - "PokeApp/Scenes/**/ViewControllers/**" # ignore ViewControlers
 - "*ViewController.swift" # ignore ViewControllers
 - "PokeApp/Scenes/**/Cells/**" # ignore ViewControlers
 - "*ViewCell.swift" # ignore ignore CollectionView and TableViewCells
