ignore:
 - "Pods/.*" # ignore pods from code coverage
 - "Libraries/.*" # ignore third party libraries from code coverage
 - "*Test/.*" # ignore Tests from code coverage
 - "**ViewController.swift" # ignore viewControllers
