ignore:
 - "Pods/.*" # ignore pods from code coverage
 - "Libraries/.*" # ignore third party libraries from code coverage
 - "*Test/.*" # ignore Tests from code coverage
 - "**.storyboard" # Storyboards
 - "PokeApp/Conveniences/UI/**" # custom UI elements
 - "PokeApp/Scenes/**/ViewControllers/**" # ignore ViewControllers
 - "*ViewController.swift" # ignore ViewControllers
 - "PokeApp/Scenes/**/Cells/**" # ignore CollectionView and TableViewCells
 - "*ViewCell.swift" # ignore CollectionView and TableViewCells
# Other Classes
 - "UIView+Loading.swift"
 - "UIViewControllerExtension.swift"
 - "AlertHelper.swift"